### PR TITLE
K8S Deployment

### PR DESCRIPTION
**Pull request by pomadchin**
This PR adds K8S Deployment manifest. 
I used `quay.io/geotrellis` org since I don't have access to `quay.io/azavea` at the moment.

### CODE REVIEW

**Review by jisantuc — APPROVED** [review]
I don't have quay.io/geotrellis credentials so I wasn't able to test a new deployment, but I _did_ move k8s to trialing because that's happening RIGHT NOW in this very PR

**Comment by pomadchin** [comment]
@jisantuc btw, it is a public repo: https://quay.io/repository/geotrellis/azavea-tech-radar?tag=latest&tab=tags

**Comment by pomadchin** [comment]
I'll wait a bit before merging this one, mb we would be able to move it into the azavea repo.

**Comment by jisantuc** [comment]
> btw, it is a public repo

I know it's public to read, but I wasn't able to push to it.

Waiting a sec to merge makes sense, it's already sufficient to do the demo tomorrow

**Comment by pomadchin** [comment]
@jisantuc updated repos to target azavea repo! Merging!

**Comment by jisantuc** [comment]
🎉

**Pull request merged**
